import ICommonOption from '@config/interfaces/ICommonOption';

export default function getBanner(generator: 'tjs' | 'tsj', option: ICommonOption) {
  if (option.noBanner) {
    return '';
  }

  if (generator === 'tjs') {
    return '// generated by tjscli: typescript-json-schema';
  }

  return '// generated by tjscli: ts-json-schema-generator';
}
