import posixJoin from '#tools/posixJoin';
import * as env from '#tools/testenv';

export default [
  {
    generator: 'tsj',
    banner: '// generated by tjscli: ts-json-schema-generator',
    filePath: posixJoin(env.exampleType01Path, 'sub', 'TStudentResp.ts'),
    formatted: '',
    typeName: 'TStudentResp',
    schema: {
      $schema: 'http://json-schema.org/draft-07/schema#',
      definitions: {
        ISubStudent: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              minLength: 2,
              maxLength: 245,
            },
            major: {
              type: 'array',
              items: {
                $ref: '#/definitions/IMajor',
              },
            },
            projessor: {
              type: 'string',
              minLength: 2,
              maxLength: 255,
            },
            college: {
              type: 'string',
              minLength: 2,
              maxLength: 255,
            },
          },
          required: ['name', 'major', 'projessor', 'college'],
        },
        IMajor: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              minLength: 2,
              maxLength: 255,
            },
            desc: {
              type: 'string',
              maxLength: 2048,
            },
          },
          required: ['name'],
        },
      },
      type: 'object',
      properties: {
        code: {
          type: 'string',
        },
        data: {
          $ref: '#/definitions/ISubStudent',
        },
      },
      required: ['code', 'data'],
    },
    reasons: [],
  },
];
